### ISSUE TITLE
Issue with GuiTransition Plugin in Godot 3.5.2: Node Not Functioning

### ISSUE THREAD

**Issue by Lawrenceku** [murikistudio/simple-gui-transitions#13] opened 2024-10-09 15:16 UTC
# Description:
I am experiencing issues with the plugin after installation in Godot 3.5.2 stable version. The plugin does not seem to work as expected.

## Steps to Reproduce:

Installed the plugin.
Enabled the plugin in the project settings.
Tried running the "layout" examples
Expected Behavior: According to the tutorial, the guitranstitions node should display specific properties and function as intended.

## Actual Behavior:

The inspector for the GuiTransition node is not showing the expected properties.
I receive an error message in the editor (attached screenshot).

## Additional Information:

I have restarted the editor multiple times.
The scripts appear to be untampered.

Attachments:

![error-gui](https://github.com/user-attachments/assets/8cead9da-7035-4e02-9429-619cfb88a6a2)

**Comment by joelgomes1994** [comment] 2024-10-09 17:14
Hello! Using the version 3.5.3 Stable I've created a brand new project, installed the plugin from the AssetLib, enabled on Project Settings and restarted the editor. It works as expected. Please, check if the Autoload is present on Project Settings as such (it should be automatically added the moment you enable the plugin):
![image](https://github.com/user-attachments/assets/7184c2a3-226b-45d9-808b-40abfd740f8e)

In the meantime, I'll investigate this on 3.5.2 Stable.

**Comment by joelgomes1994** [comment] 2024-10-09 17:22
Yeah, I tested on 3.5.2 Stable and could not reproduce the issue. Try disabling the plugin, enabling it again and reloading the project, it should add the Autoload automatically once you enable the plugin. Also, once the plugin is enabled and the project reloaded, check if all the settings are added to the Project Settings here:
![image](https://github.com/user-attachments/assets/d792b2b2-8c4b-4196-b02e-8f4a44b6d906)

**Comment by Lawrenceku** [comment] 2024-10-09 17:25
I think your snip solved this. 
As it turns out, enabling the plugin didn’t automatically add the singleton to autoload for me, so I just added it manually, and now it works like a charm
Arigatou!

**Comment by joelgomes1994** [comment] 2024-10-09 21:43
Nice! I'll close this issue then, thanks for the contact!

**Closed as completed by joelgomes1994** 2024-10-09 21:43 UTC
